service: lambda-caching-s3

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-plugin-typescript

functions:
  lambdaCacheExample:
    handler: src/index.cacheHandlerLambda
    events:
      - http:
          method: GET
          path: api
